/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
/**
 *
 * @author kris
 */
public class Cafe_Management_System extends javax.swing.JFrame {
double [] drink = new double[12];
double [] treat = new double[10];
String [] cost = new String[3];
double [] i = new double[12];

    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jChxAffogato = new javax.swing.JCheckBox();
        jChxAmer = new javax.swing.JCheckBox();
        jChxBreve = new javax.swing.JCheckBox();
        jChxCappu = new javax.swing.JCheckBox();
        jChxDoppio = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTxtBreve = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTxtAffogato = new javax.swing.JEditorPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTxtAmer = new javax.swing.JEditorPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTxtCappu = new javax.swing.JEditorPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTxtDoppio = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jChxEspress = new javax.swing.JCheckBox();
        jChxLatte = new javax.swing.JCheckBox();
        jChxMacc = new javax.swing.JCheckBox();
        jChxRistretto = new javax.swing.JCheckBox();
        jChxPanna = new javax.swing.JCheckBox();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTxtEspress = new javax.swing.JEditorPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTxtLatte = new javax.swing.JEditorPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTxtMacc = new javax.swing.JEditorPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTxtRistretto = new javax.swing.JEditorPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTxtPanna = new javax.swing.JEditorPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtReceipt = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabelTaxes = new javax.swing.JLabel();
        jLabelSubTote = new javax.swing.JLabel();
        jLabelTotale = new javax.swing.JLabel();
        jLabelTax = new javax.swing.JLabel();
        jLabelSubT = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabelDrinks = new javax.swing.JLabel();
        jLabelTreats = new javax.swing.JLabel();
        jLabelServChrg = new javax.swing.JLabel();
        jTxtCostDrink = new javax.swing.JLabel();
        jTxtCostTreats = new javax.swing.JLabel();
        jTxtServCharge = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jChxCrois = new javax.swing.JCheckBox();
        jChxCheez = new javax.swing.JCheckBox();
        jChxBost = new javax.swing.JCheckBox();
        jChxCoffCake = new javax.swing.JCheckBox();
        jChxCpop = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtBost = new javax.swing.JEditorPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTxtCpop = new javax.swing.JEditorPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTxtCheez = new javax.swing.JEditorPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTxtCoffCake = new javax.swing.JEditorPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTxtCrois = new javax.swing.JEditorPane();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1360, 980));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("The Java Stop");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jChxAffogato.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxAffogato.setText("Affogato");
        jChxAffogato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jChxAffogato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxAffogatoActionPerformed(evt);
            }
        });

        jChxAmer.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxAmer.setText("Americano");
        jChxAmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxAmerActionPerformed(evt);
            }
        });

        jChxBreve.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxBreve.setText("Breve");
        jChxBreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxBreveActionPerformed(evt);
            }
        });

        jChxCappu.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxCappu.setText("Cappucino");
        jChxCappu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxCappuActionPerformed(evt);
            }
        });

        jChxDoppio.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxDoppio.setText("Doppio");
        jChxDoppio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxDoppioActionPerformed(evt);
            }
        });

        jTxtBreve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtBreve.setText("0");
        jTxtBreve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtBreveMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTxtBreve);

        jTxtAffogato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtAffogato.setText("0");
        jTxtAffogato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtAffogatoMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTxtAffogato);

        jTxtAmer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtAmer.setText("0");
        jTxtAmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtAmerMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTxtAmer);

        jTxtCappu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCappu.setText("0");
        jTxtCappu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCappuMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jTxtCappu);

        jTxtDoppio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtDoppio.setText("0");
        jTxtDoppio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtDoppioMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(jTxtDoppio);

        jLabel2.setText("Quantity");

        jLabel7.setText("Item");

        jLabel3.setText("Price");

        jLabel15.setText("$2.00");

        jLabel16.setText("$2.50");

        jLabel17.setText("$2.00");

        jLabel18.setText("$1.00");

        jLabel19.setText("$4.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChxAmer)
                    .addComponent(jChxDoppio)
                    .addComponent(jChxBreve)
                    .addComponent(jChxAffogato)
                    .addComponent(jChxCappu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jChxAffogato)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jChxAmer)
                                .addComponent(jLabel16))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jChxBreve)
                                .addComponent(jLabel17))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jChxCappu)
                                .addComponent(jLabel18))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jChxDoppio))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 360, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jChxEspress.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxEspress.setText("Espresso");
        jChxEspress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxEspressActionPerformed(evt);
            }
        });

        jChxLatte.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxLatte.setText("Latte");
        jChxLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxLatteActionPerformed(evt);
            }
        });

        jChxMacc.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxMacc.setText("Macchiato");
        jChxMacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxMaccActionPerformed(evt);
            }
        });

        jChxRistretto.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxRistretto.setText("Ristretto");
        jChxRistretto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxRistrettoActionPerformed(evt);
            }
        });

        jChxPanna.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxPanna.setText("Panna");
        jChxPanna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxPannaActionPerformed(evt);
            }
        });

        jTxtEspress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtEspress.setText("0");
        jTxtEspress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtEspressMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(jTxtEspress);

        jTxtLatte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtLatte.setText("0");
        jTxtLatte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtLatteMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(jTxtLatte);

        jTxtMacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtMacc.setText("0");
        jTxtMacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtMaccMouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(jTxtMacc);

        jTxtRistretto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtRistretto.setText("0");
        jTxtRistretto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtRistrettoMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(jTxtRistretto);

        jTxtPanna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtPanna.setText("0");
        jTxtPanna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtPannaMouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(jTxtPanna);

        jLabel9.setText("Item");

        jLabel8.setText("Quantity");

        jLabel21.setText("$0.90");

        jLabel24.setText("$5.00");

        jLabel20.setText("Price");

        jLabel22.setText("$2.00");

        jLabel25.setText("$4.00");

        jLabel23.setText("$2.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jChxPanna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChxEspress)
                            .addComponent(jChxLatte)
                            .addComponent(jChxRistretto)
                            .addComponent(jChxMacc)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel20)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jChxEspress)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addComponent(jChxLatte))
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChxMacc))
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChxRistretto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jChxPanna)
                        .addComponent(jLabel25))
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 380, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTxtReceipt.setColumns(20);
        jTxtReceipt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jTxtReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 490, 640));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTaxes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTaxes.setText("Tax");

        jLabelSubTote.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelSubTote.setText("Subtotal");

        jLabelTotale.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotale.setText("Total");

        jLabelTax.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTax.setText("0");
        jLabelTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTax.setOpaque(true);

        jLabelSubT.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSubT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSubT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubT.setText("0");
        jLabelSubT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelSubT.setOpaque(true);

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal.setText("0");
        jLabelTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelTotal.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTaxes)
                    .addComponent(jLabelSubTote)
                    .addComponent(jLabelTotale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSubT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTax)
                    .addComponent(jLabelTaxes))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubT)
                    .addComponent(jLabelSubTote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTotale))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 320, 170));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBtnTotal)
                .addGap(18, 18, 18)
                .addComponent(jBtnReceipt)
                .addGap(18, 18, 18)
                .addComponent(jBtnReset)
                .addGap(31, 31, 31)
                .addComponent(jBtnExit)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTotal)
                    .addComponent(jBtnReceipt)
                    .addComponent(jBtnExit)
                    .addComponent(jBtnReset))
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 760, 480, 60));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelDrinks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelDrinks.setText("Cost of Drinks");

        jLabelTreats.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTreats.setText("Cost of Treats");

        jLabelServChrg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelServChrg.setText("Service Charge");

        jTxtCostDrink.setBackground(new java.awt.Color(255, 255, 255));
        jTxtCostDrink.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtCostDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtCostDrink.setText("0");
        jTxtCostDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCostDrink.setOpaque(true);

        jTxtCostTreats.setBackground(new java.awt.Color(255, 255, 255));
        jTxtCostTreats.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtCostTreats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtCostTreats.setText("0");
        jTxtCostTreats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCostTreats.setOpaque(true);

        jTxtServCharge.setBackground(new java.awt.Color(255, 255, 255));
        jTxtServCharge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtServCharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtServCharge.setText("0");
        jTxtServCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtServCharge.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDrinks)
                    .addComponent(jLabelTreats)
                    .addComponent(jLabelServChrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTxtCostDrink, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTxtCostTreats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtServCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTxtCostDrink)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelDrinks)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTreats)
                            .addComponent(jTxtCostTreats))))
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtServCharge)
                    .addComponent(jLabelServChrg))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 320, 170));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jChxCrois.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxCrois.setText("Croissant");
        jChxCrois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxCroisActionPerformed(evt);
            }
        });

        jChxCheez.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxCheez.setText("Cheesecake");
        jChxCheez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxCheezActionPerformed(evt);
            }
        });

        jChxBost.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxBost.setText("Boston Cream Pie");
        jChxBost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxBostActionPerformed(evt);
            }
        });

        jChxCoffCake.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxCoffCake.setText("Coffee Cake");
        jChxCoffCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxCoffCakeActionPerformed(evt);
            }
        });

        jChxCpop.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jChxCpop.setText("Cake Pop");
        jChxCpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChxCpopActionPerformed(evt);
            }
        });

        jLabel14.setText("Quantity");

        jLabel13.setText("Item");

        jLabel32.setText("Price");

        jLabel33.setText("$3.00");

        jLabel34.setText("$1.50");

        jLabel35.setText("$2.25");

        jLabel36.setText("$1.50");

        jLabel37.setText("$1.00");

        jTxtBost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtBost.setText("0");
        jTxtBost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtBostMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTxtBost);

        jTxtCpop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCpop.setText("0");
        jTxtCpop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCpopMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(jTxtCpop);

        jTxtCheez.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCheez.setText("0");
        jTxtCheez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCheezMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(jTxtCheez);

        jTxtCoffCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCoffCake.setText("0");
        jTxtCoffCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCoffCakeMouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(jTxtCoffCake);

        jTxtCrois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtCrois.setText("0");
        jTxtCrois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCroisMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(jTxtCrois);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChxCpop)
                            .addComponent(jChxCheez)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jChxCrois)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jChxBost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jChxCoffCake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel36)))
                .addGap(109, 109, 109)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane18)
                    .addComponent(jScrollPane19)
                    .addComponent(jScrollPane20)
                    .addComponent(jScrollPane21)
                    .addComponent(jScrollPane4))
                .addGap(100, 100, 100))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel32))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jChxBost)
                                                .addComponent(jLabel33))
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jChxCpop)
                                            .addComponent(jLabel34)))
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jChxCheez)
                                    .addComponent(jLabel35)))
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jChxCoffCake)))
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jChxCrois)
                        .addComponent(jLabel37))
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 650, 270));
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChxAffogatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxAffogatoActionPerformed
        // TODO add cost of item here:
        double cAff = Double.parseDouble(jTxtCostDrink.getText());
        double Affogato = Double.parseDouble(jTxtAffogato.getText());
        double iAffo = 2.0;
        
        if (jChxAffogato.isSelected()){
            i[0] = (Affogato * iAffo)+ cAff;
            String pDrink = String.format("%.2f", i[0]);
            jTxtCostDrink.setText(pDrink);
            //jTxtAffogato.setText(pDrink);
        }
    }//GEN-LAST:event_jChxAffogatoActionPerformed

    private void jChxAmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxAmerActionPerformed
        // TODO add cost of item here:
        double cAmericano = Double.parseDouble(jTxtCostDrink.getText());
        double Americano = Double.parseDouble(jTxtAmer.getText());
        double iAmericano = 2.50;
        
        if (jChxAmer.isSelected()){
            i[1] = (Americano * iAmericano)+ cAmericano;
            String pDrink = String.format("%.2f", i[1]);
            jTxtCostDrink.setText(pDrink);
            //jTxtAmer.setText(pDrink);
        }
    }//GEN-LAST:event_jChxAmerActionPerformed

    private void jChxCappuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxCappuActionPerformed
        // TODO add cost of item:
        double cCappu = Double.parseDouble(jTxtCostDrink.getText());
        double Cappucino = Double.parseDouble(jTxtCappu.getText());
        double iCappu = 1.0;
        
        if (jChxCappu.isSelected()){
            i[3] = (Cappucino * iCappu)+ cCappu;
            String pDrink = String.format("%.2f", i[3]);
            jTxtCostDrink.setText(pDrink);
           // jTxtCappu.setText(pDrink);
        }
    }//GEN-LAST:event_jChxCappuActionPerformed

    private void jChxRistrettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxRistrettoActionPerformed
        // TODO add your handling code here:
        double cRistretto = Double.parseDouble(jTxtCostDrink.getText());
        double Ristretto = Double.parseDouble(jTxtRistretto.getText());
        double iRistretto = 5.0;
        
        if (jChxRistretto.isSelected()){
            i[8] = (Ristretto * iRistretto)+ cRistretto;
            String pDrink = String.format("%.2f", i[8]);
            jTxtCostDrink.setText(pDrink);
            //jTxtRistretto.setText(pDrink);
        }
    }//GEN-LAST:event_jChxRistrettoActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
            drink [0] = Double.parseDouble(jTxtCostDrink.getText());
            drink [1] = Double.parseDouble(jTxtCostTreats.getText());
            drink [2] = Double.parseDouble(jTxtServCharge.getText());
        //Totalling the costs
            double cTotal1 = (drink[0] + drink[1] + drink[2]);
            String iTaxTotal = String.format("$ %.2f", cTotal1 / 100);
            jLabelTax.setText(iTaxTotal);
            double subTotal = (cTotal1);
            String iSubTotal = String.format("$ %.2f", subTotal);
            jLabelSubT.setText(iSubTotal);
            double allTotal = (cTotal1);
            String iTotal = String.format("$ % .2f", allTotal + (allTotal/100));
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        // TODO add your handling code here:
        // Drink, treat, and serv charge index of
       
//drinks
//        drink[0] = Double.parseDouble(jTxtAffogato.getText());
//        drink[1] = Double.parseDouble(jTxtAmer.getText());
//        drink[2] = Double.parseDouble(jTxtBreve.getText());
//        drink[3] = Double.parseDouble(jTxtCappu.getText());
//        drink[4] = Double.parseDouble(jTxtDoppio.getText());
//        drink[5] = Double.parseDouble(jTxtEspress.getText());
//        drink[6] = Double.parseDouble(jTxtLatte.getText());
//        drink[7] = Double.parseDouble(jTxtMacc.getText());
//        drink[8] = Double.parseDouble(jTxtRistretto.getText());
//        drink[9] = Double.parseDouble(jTxtPanna.getText());
//        //treats
//        treat[0] = Double.parseDouble(jTxtBost.getText());
//        treat[1] = Double.parseDouble(jTxtCpop.getText());
//        treat[2] = Double.parseDouble(jTxtCheez.getText());
//        treat[3] = Double.parseDouble(jTxtCoffCake.getText());
//        treat[4] = Double.parseDouble(jTxtCrois.getText());
        //cost
        cost[0] = jLabelTax.getText();
        cost[1] = jLabelSubT.getText();
        cost[2] = jLabelTotal.getText();
        //ref
        int refs = 1355 + (int) (Math.random()* 4238);
        
        

            //calendar info
            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
            tTime.format(timer.getTime());
            SimpleDateFormat tDate = new SimpleDateFormat("dd-MM-yyyy");
            tDate.format(timer.getTime());
        //receipt
        jTxtReceipt.append(
                "\n\tJava Stop Cafe \n" +
                "\n Reference: #" + refs +
                "\n ~~~~~~~~~~~~~~~~~~~~~~~~ " +
                        "\nItem\tPrice            Quantity" +
                "\nAffogato:\t\t" + drink[0] + 
                "\nAmericano:\t\t" + drink[1] +
                "\nBreve:\t\t" + drink[2] +
                "\nCappuccino:\t\t" + drink[3] +
                "\nDoppio:\t\t" + drink[4] +
                "\nEspress:\t\t" + drink[5] +
                "\nLatte:\t\t" + drink[6] +
                "\nMacc:\t\t" + drink[7] +
                "\nRistretto:\t\t" + drink[8] +
                "\nPanna:\t\t" + drink[9] +
                "\n --------------------------------------\n" +
                        "\nItem\tPrice            Quantity" +
                        "\nTreats:\t\t\t\t" + 
                        "\nBoston Cream Pie:\t" + treat[0] +
                        "\nCake Pop:\t\t" + treat[1]+
                        "\nCheesecake:\t\t" + treat[2] +
                        "\nCoffee Cake:\t\t" + treat[3] + 
                        "\nCroissant:\t\t" + treat[4] + 
                        "\n --------------------------------------\n" +
                        "\nTax: " + cost[0] +
                        "\nSubtotal: " + cost[1] +
                        "\nTotal: " + cost[2] +
                        "\n --------------------------------------\n" +
                        "\nDate:" + tDate.format(timer.getTime()) + 
                        "\nTime " + tTime.format(timer.getTime()) +
                        "\n\nThank you!");
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jChxCoffCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxCoffCakeActionPerformed
        // TODO add your handling code here:
        double cCoffCake = Double.parseDouble(jTxtCostTreats.getText());
        double CoffeeCake = Double.parseDouble(jTxtCoffCake.getText());
        double iCoffCake = 2.0;
        
        if (jChxCoffCake.isSelected()){
            i[3] = (CoffeeCake * iCoffCake)+ cCoffCake;
            String pTreat = String.format("%.2f", i[3]);
            jTxtCostTreats.setText(pTreat);
            //jTxtCoffCake.setText(pTreat);
        }
    }//GEN-LAST:event_jChxCoffCakeActionPerformed

    private void jChxBostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxBostActionPerformed
        // TODO add your handling code here:
        double cBost = Double.parseDouble(jTxtCostTreats.getText());
        double BostonCream = Double.parseDouble(jTxtBost.getText());
        double iBost = 3.0;
        
        if (jChxBost.isSelected()){
            i[0] = (BostonCream * iBost)+ cBost;
            String pTreat = String.format("%.2f", i[0]);
            jTxtCostTreats.setText(pTreat);
            //jTxtBost.setText(pTreat);
        }
    }//GEN-LAST:event_jChxBostActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        //labels
//        jLabelTreats.setText(null);
//        jLabelDrinks.setText(null);
//        jLabelServChrg.setText(null);
//        jLabelTax.setText(null);
//        jLabelTotal.setText(null);
//        jLabelSubT.setText(null);
        //Checkboxes (Chx)
        jChxAffogato.setSelected(false);
        jChxAmer.setSelected(false);
        jChxBreve.setSelected(false);
        jChxCappu.setSelected(false);
        jChxDoppio.setSelected(false);
        jChxEspress.setSelected(false);
        jChxLatte.setSelected(false);
        jChxMacc.setSelected(false);
        jChxPanna.setSelected(false);
        jChxRistretto.setSelected(false);
        jChxBost.setSelected(false);
        jChxCheez.setSelected(false);
        jChxCoffCake.setSelected(false);
        jChxCpop.setSelected(false);
        jChxCrois.setSelected(false);
        //Text boxes (Txt)
        jTxtReceipt.setText(null);
        jTxtAffogato.setText("0");
        jTxtAmer.setText("0");
        jTxtBreve.setText("0");
        jTxtCappu.setText("0");
        jTxtDoppio.setText("0");
        jTxtEspress.setText("0");
        jTxtLatte.setText("0");
        jTxtMacc.setText("0");
        jTxtPanna.setText("0");
        jTxtRistretto.setText("0");
        jTxtBost.setText("0");
        jTxtCheez.setText("0");
        jTxtCoffCake.setText("0");
        jTxtCpop.setText("0");
        jTxtCrois.setText("0");
        //label for cost + totals
        jLabelTax.setText("0");
        jLabelSubT.setText("0");
        jLabelTotal.setText("0");
        //Cost of items
        jTxtCostDrink.setText("0");
        jTxtCostTreats.setText("0");
        jTxtServCharge.setText("0");
        
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jChxBreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxBreveActionPerformed
        // TODO add cost of item here:
        double cBreve = Double.parseDouble(jTxtCostDrink.getText());
        double Breve = Double.parseDouble(jTxtBreve.getText());
        double iBreve = 2.0;
        
        if (jChxBreve.isSelected()){
            i[2] = (Breve * iBreve)+ cBreve;
            String pDrink = String.format("%.2f", i[2]);
            jTxtCostDrink.setText(pDrink);
            //jTxtBreve.setText(pDrink);
        }
    }//GEN-LAST:event_jChxBreveActionPerformed

    private void jChxDoppioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxDoppioActionPerformed
        // TODO add cost of item here:
        double cDoppio = Double.parseDouble(jTxtCostDrink.getText());
        double Doppio = Double.parseDouble(jTxtDoppio.getText());
        double iDoppio = 4.0;
        
        if (jChxDoppio.isSelected()){
            i[4] = (Doppio * iDoppio)+ cDoppio;
            String pDrink = String.format("%.2f", i[4]);
            jTxtCostDrink.setText(pDrink);
            //jTxtDoppio.setText(pDrink);
        }
    }//GEN-LAST:event_jChxDoppioActionPerformed

    private void jChxEspressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxEspressActionPerformed
        // TODO add cost of item here:
        double cEspresso = Double.parseDouble(jTxtCostDrink.getText());
        double Espress = Double.parseDouble(jTxtEspress.getText());
        double iEspress = 0.90;
        
        if (jChxEspress.isSelected()){
            i[5] = (Espress * iEspress)+ cEspresso;
            String pDrink = String.format("%.2f", i[5]);
            jTxtCostDrink.setText(pDrink);
            //jTxtEspress.setText(pDrink);
        }
    }//GEN-LAST:event_jChxEspressActionPerformed

    private void jChxLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxLatteActionPerformed
        // TODO add cost of item here:
        double cLatte = Double.parseDouble(jTxtCostDrink.getText());
        double Latte = Double.parseDouble(jTxtLatte.getText());
        double iLatte = 2.0;
        
        if (jChxLatte.isSelected()){
            i[6] = (Latte * iLatte)+ cLatte;
            String pDrink = String.format("%.2f", i[6]);
            jTxtCostDrink.setText(pDrink);
            //jTxtLatte.setText(pDrink);
        }
    }//GEN-LAST:event_jChxLatteActionPerformed

    private void jChxMaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxMaccActionPerformed
        // TODO add cost of item here:
        double cMacc = Double.parseDouble(jTxtCostDrink.getText());
        double Macchiato = Double.parseDouble(jTxtLatte.getText());
        double iMacc = 2.0;
        
        if (jChxMacc.isSelected()){
            i[7] = (Macchiato * iMacc)+ cMacc;
            String pDrink = String.format("%.2f", i[7]);
            jTxtCostDrink.setText(pDrink);
           // jTxtMacc.setText(pDrink);
        }
    }//GEN-LAST:event_jChxMaccActionPerformed

    private void jChxPannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxPannaActionPerformed
        // TODO add your handling code here:
        double cPanna = Double.parseDouble(jTxtCostDrink.getText());
        double Panna = Double.parseDouble(jTxtPanna.getText());
        double iPanna = 4.0;
        
        if (jChxPanna.isSelected()){
            i[9] = (Panna * iPanna)+ cPanna;
            String pDrink = String.format("%.2f", i[9]);
            jTxtCostDrink.setText(pDrink);
            //jTxtPanna.setText(pDrink);
        }
    }//GEN-LAST:event_jChxPannaActionPerformed

    private void jChxCpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxCpopActionPerformed
        // TODO add your handling code here:
        double cCakepop = Double.parseDouble(jTxtCostTreats.getText());
        double Cpop = Double.parseDouble(jTxtCpop.getText());
        double iCpop = 1.5;
        
        if (jChxCpop.isSelected()){
            i[1] = (Cpop * iCpop)+ cCakepop;
            String pTreat = String.format("%.2f", i[1]);
            jTxtCostTreats.setText(pTreat);
            //jTxtCpop.setText(pTreat);
        }
    }//GEN-LAST:event_jChxCpopActionPerformed

    private void jChxCheezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxCheezActionPerformed
        // TODO add your handling code here:
        double cCheeze = Double.parseDouble(jTxtCostTreats.getText());
        double CheeseCake = Double.parseDouble(jTxtCheez.getText());
        double iCheeze = 1.5;
        
        if (jChxCheez.isSelected()){
            i[2] = (CheeseCake * iCheeze)+ cCheeze;
            String pTreat = String.format("%.2f", i[2]);
            jTxtCostTreats.setText(pTreat);
            //jTxtCheez.setText(pTreat);
        }
    }//GEN-LAST:event_jChxCheezActionPerformed

    private void jChxCroisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChxCroisActionPerformed
        // TODO add your handling code here:
        double cCrois = Double.parseDouble(jTxtCostTreats.getText());
        double Crois = Double.parseDouble(jTxtCrois.getText());
        double iCrois = 1.0;
        
        if (jChxCrois.isSelected()){
            i[4] = (Crois * iCrois)+ cCrois;
            String pTreat = String.format("%.2f", i[4]);
            jTxtCostTreats.setText(pTreat);
            //jTxtCrois.setText(pTreat);
        }
    }//GEN-LAST:event_jChxCroisActionPerformed

    private void jTxtAffogatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtAffogatoMouseClicked
        // TODO set text to null when clicked:
        jTxtAffogato.setText(null);
    }//GEN-LAST:event_jTxtAffogatoMouseClicked

    private void jTxtAmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtAmerMouseClicked
        // TODO set text to null when clicked:
        jTxtAmer.setText(null);
    }//GEN-LAST:event_jTxtAmerMouseClicked

    private void jTxtBreveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtBreveMouseClicked
        // TODO set text to null when clicked:
        jTxtBreve.setText(null);
    }//GEN-LAST:event_jTxtBreveMouseClicked

    private void jTxtCappuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCappuMouseClicked
        // TODO set text to null when clicked:
        jTxtCappu.setText(null);
    }//GEN-LAST:event_jTxtCappuMouseClicked

    private void jTxtDoppioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtDoppioMouseClicked
        // TODO set text to null when clicked:
        jTxtDoppio.setText(null);
    }//GEN-LAST:event_jTxtDoppioMouseClicked

    private void jTxtEspressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtEspressMouseClicked
        // TODO set text to null when clicked:
        jTxtEspress.setText(null);
    }//GEN-LAST:event_jTxtEspressMouseClicked

    private void jTxtLatteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtLatteMouseClicked
        // TODO set text to null when clicked:
        jTxtLatte.setText(null);
    }//GEN-LAST:event_jTxtLatteMouseClicked

    private void jTxtMaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtMaccMouseClicked
        // TODO set text to null when clicked:
        jTxtMacc.setText(null);
    }//GEN-LAST:event_jTxtMaccMouseClicked

    private void jTxtRistrettoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtRistrettoMouseClicked
        // TODO set text to null when clicked:
        jTxtRistretto.setText(null);
    }//GEN-LAST:event_jTxtRistrettoMouseClicked

    private void jTxtPannaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtPannaMouseClicked
        // TODO set text to null when clicked:
        jTxtPanna.setText(null);
    }//GEN-LAST:event_jTxtPannaMouseClicked

    private void jTxtBostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtBostMouseClicked
        // TODO set text to null when clicked:
        jTxtBost.setText(null);
    }//GEN-LAST:event_jTxtBostMouseClicked

    private void jTxtCpopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCpopMouseClicked
        // TODO set text to null when clicked:
        jTxtCpop.setText(null);
    }//GEN-LAST:event_jTxtCpopMouseClicked

    private void jTxtCheezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCheezMouseClicked
        // TODO set text to null when clicked:
        jTxtCheez.setText(null);
    }//GEN-LAST:event_jTxtCheezMouseClicked

    private void jTxtCoffCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCoffCakeMouseClicked
        // TODO set text to null when clicked:
        jTxtCoffCake.setText(null);
    }//GEN-LAST:event_jTxtCoffCakeMouseClicked

    private void jTxtCroisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCroisMouseClicked
        // TODO set text to null when clicked:
        jTxtCrois.setText(null);
    }//GEN-LAST:event_jTxtCroisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChxAffogato;
    private javax.swing.JCheckBox jChxAmer;
    private javax.swing.JCheckBox jChxBost;
    private javax.swing.JCheckBox jChxBreve;
    private javax.swing.JCheckBox jChxCappu;
    private javax.swing.JCheckBox jChxCheez;
    private javax.swing.JCheckBox jChxCoffCake;
    private javax.swing.JCheckBox jChxCpop;
    private javax.swing.JCheckBox jChxCrois;
    private javax.swing.JCheckBox jChxDoppio;
    private javax.swing.JCheckBox jChxEspress;
    private javax.swing.JCheckBox jChxLatte;
    private javax.swing.JCheckBox jChxMacc;
    private javax.swing.JCheckBox jChxPanna;
    private javax.swing.JCheckBox jChxRistretto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDrinks;
    private javax.swing.JLabel jLabelServChrg;
    private javax.swing.JLabel jLabelSubT;
    private javax.swing.JLabel jLabelSubTote;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTaxes;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotale;
    private javax.swing.JLabel jLabelTreats;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JEditorPane jTxtAffogato;
    private javax.swing.JEditorPane jTxtAmer;
    private javax.swing.JEditorPane jTxtBost;
    private javax.swing.JEditorPane jTxtBreve;
    private javax.swing.JEditorPane jTxtCappu;
    private javax.swing.JEditorPane jTxtCheez;
    private javax.swing.JEditorPane jTxtCoffCake;
    private javax.swing.JLabel jTxtCostDrink;
    private javax.swing.JLabel jTxtCostTreats;
    private javax.swing.JEditorPane jTxtCpop;
    private javax.swing.JEditorPane jTxtCrois;
    private javax.swing.JEditorPane jTxtDoppio;
    private javax.swing.JEditorPane jTxtEspress;
    private javax.swing.JEditorPane jTxtLatte;
    private javax.swing.JEditorPane jTxtMacc;
    private javax.swing.JEditorPane jTxtPanna;
    private javax.swing.JTextArea jTxtReceipt;
    private javax.swing.JEditorPane jTxtRistretto;
    private javax.swing.JLabel jTxtServCharge;
    // End of variables declaration//GEN-END:variables
}
